### ISSUE TITLE
 Failed to bind properties under 'spring.config'

### ISSUE THREAD

**Issue by ndy2** [prgrms-web-devcourse/Team-Meoguri-Linkocean-BE#26]
![image](https://user-images.githubusercontent.com/67302707/180828331-fa243fba-fe23-40f4-b9f4-c372f7022343.png)

이거 왜 발생하는 거죠?!

**Comment by jk05018** [comment]
빌드한 뒤 그냥 실행만 했나요?

**Comment by jk05018** [comment]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/68465557/180915423-cb0928dc-770e-403c-945d-0405e71b6b34.png">
저는 가장 최근 커밋까지 pull하고 도커를 돌려도 정상 작동하는데 영문을 잘 모르겠네요..! 이따 얘기해 보죠!

**Comment by hyuk0309** [comment]
저는 잘 동작합니다!
<img width="1259" alt="스크린샷 2022-07-26 오후 12 54 56" src="https://user-images.githubusercontent.com/29492667/180919607-103bb831-f0de-4bba-80c4-1ae6d9bed0be.png">

**Comment by ndy2** [comment]
`docker-compose up --build`
!!
