### ISSUE TITLE
Architecture Violation

### ISSUE THREAD

**Issue by hyuk0309** [prgrms-web-devcourse/Team-Meoguri-Linkocean-BE#28]
북마크 링크데이터를 일주일에 한번 동기화 시켜주는 스케줄러를 개발했습니다. 

스케줄러 위치
<img width="441" alt="스크린샷 2022-07-26 오전 10 31 27" src="https://user-images.githubusercontent.com/29492667/180903259-0ef36ac2-dc43-4c11-aade-7fe6c07cf4de.png">

스케줄러 코드
<img width="1074" alt="스크린샷 2022-07-26 오전 10 31 41" src="https://user-images.githubusercontent.com/29492667/180903300-de2325f4-2144-4398-a8f8-7d14fd4b039c.png">

위와 같이 스케줄러를 가져갔더니, 의존성 테스트에서 실패합니다.

> Architecture Violation [Priority: MEDIUM] - Rule 'no classes that reside in a package 'com.meoguri.linkocean.infrastructure..' should depend on classes that reside in any package ['com.meoguri.linkocean.domain..']' was violated (3 times):

우기팀 AirCnC를 참고 스케줄러를 등록했는데, 적절한 위치를 어디로 할지 고민이네요 🤔

**Comment by ndy2** [comment]
아 이부분에 대해서 저희가 반영하진 않았지만 최종적으로 scheduler의 위치는 infra 가 아닌 해당 domain 패키지가 적절할 것 같다는
피드백을 들었었습니다.

그래서 domain 패키지에 작성하면 괜찮을 것 같아요.

추가로 link(linkMetadata) 가 좀 커지는 만큼 domain 패키지를 분리하는 것이 좋을 것 같습니다.
이부분은 만나서 같이 진행해보시죠
